version: '3.0'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"

  postgres:
    build: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  auth_service:
    build: ./auth_service
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  upload_service:
    build: ./upload_service
    ports:
      - "5001:5001"
    depends_on:
      - rabbitmq

  file_management_service:
    build: ./file_management_service
    ports:
      - "5002:5002"
    depends_on:
      - postgres

volumes:
  postgres-data:
