version: '4.0'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"

  postgres:
    build: ./postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
    ports:
      - "5432:5432"

  auth_service:
    build: ./auth_service
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - rabbitmq

  file_management_service:
    build: ./file_management_service
    ports:
      - "5002:5002"
    environment:
      - ENCRYPTION_KEY=WX78XrhcWEcPgqbZ7C/Aq7tokjleyQvc5LBx7luBn3A=
    depends_on:
      - postgres
      - rabbitmq

