server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: auth_service
    static_configs:
      - targets:
          - localhost
        labels:
          job: auth_service
          __path__: /dummy/auth_service.log
    pipeline_stages:
      - json:
          expressions:
            levelname: levelname
            message: message
            asctime: asctime
            name: name
            headers: headers
            body: body
            status: status
      - labels:
            level: levelname
            time: asctime
            name: name
            body: body
            headers: headers
            status: status
      - output:
            source: message

