CREATE TABLE IF NOT EXISTS files (
    id SERIAL PRIMARY KEY,
    username TEXT NOT NULL,
    filename TEXT NOT NULL,
    content TEXT NOT NULL,
    iv TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    password_hash TEXT UNIQUE NOT NULL,
    salt TEXT UNIQUE NOT NULL
);
